#! /usr/bin/env node
var fs = require('fs');
console.log(process.argv[1]);
var Haiku = require('../lib/main.js');

var msgPath = process.argv[2];
fs.readFile(msgPath, 'utf8', function(err, msg) {
  var haiku = msg = msg.trim();
  // var haiku = Haiku.makeHaiku ? Haiku.makeHaiku(msg) : msg;
  var test = Haiku.makeHaiku(haiku);
  console.log(test)
  if (Haiku.isHaiku(msg)) {
    haiku += ' is a haiku';
  } 

  fs.writeFile(msgPath, haiku, function() {
    process.exit(0);
  });
});


// breaking when too short (not three arrays)
// breaking at add words