#! /usr/bin/env node
fs = require('fs');
console.log(process.argv[1]);
var makeHaiku = require('../lib/main.js').makeHaiku;

var msgPath = process.argv[2];
fs.readFile(msgPath, 'utf8', function(err, msg) {
	msg = msg.trim();
	var haiku = makeHaiku ? makeHaiku(msg) : msg;
	fs.writeFile(msgPath, haiku, function(err) {
		process.exit(0);
	});
});
