#! /usr/bin/env node
var fs = require('fs');
var Haiku = require('../lib/main.js');

var msgPath = process.argv[2];
fs.readFile(msgPath, 'utf8', function(err, msg) {
  var haiku = msg = msg.trim();
  var haiku = Haiku.makeHaiku ? Haiku.makeHaiku(msg) : msg;

  fs.writeFile(msgPath, haiku, function() {
    process.exit(0);
  });
});
